/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pay/wxrefund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 微信退款 */
        post: operations["wxrefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pay/wxrefundNotify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 微信退款回调 */
        post: operations["handleWeChatPayRefund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pay/wxpayNotify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 微信支付成功回调 */
        post: operations["handleWeChatPayTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pay/wxpayByPayCode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 微信付款码支付 */
        post: operations["wxpayByPayCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pay/wxjsapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 微信支付 */
        post: operations["wxjsapi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pay/aliPay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["aliPay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pay/payment/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getpayconfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/callback/config/callback/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCallBackConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AmountReq: {
            /** Format: int64 */
            refund?: number;
            from?: components["schemas"]["FundsFromItem"][];
            /** Format: int64 */
            total?: number;
            currency?: string;
        };
        FundsFromItem: {
            /** Format: int64 */
            amount?: number;
            /** @enum {string} */
            account?: "AVAILABLE" | "UNAVAILABLE";
        };
        GoodsDetail: {
            merchantGoodsId?: string;
            wechatpayGoodsId?: string;
            goodsName?: string;
            /** Format: int64 */
            unitPrice?: number;
            /** Format: int64 */
            refundAmount?: number;
            /** Format: int32 */
            refundQuantity?: number;
        };
        /** @description 退款时传递的参数 */
        RefundDto: {
            /**
             * Format: int32
             * @description 业务类型
             */
            businessType?: number;
            transactionId?: string;
            outTradeNo?: string;
            outRefundNo?: string;
            reason?: string;
            notifyUrl?: string;
            goodsDetail?: components["schemas"]["GoodsDetail"][];
            amount?: components["schemas"]["AmountReq"];
            /** @enum {string} */
            fundsAccount?: "AVAILABLE";
        };
        Amount: {
            /** Format: int64 */
            total?: number;
            /** Format: int64 */
            refund?: number;
            from?: components["schemas"]["FundsFromItem"][];
            /** Format: int64 */
            payerTotal?: number;
            /** Format: int64 */
            payerRefund?: number;
            /** Format: int64 */
            settlementRefund?: number;
            /** Format: int64 */
            settlementTotal?: number;
            /** Format: int64 */
            discountRefund?: number;
            currency?: string;
            /** Format: int64 */
            refundFee?: number;
        };
        Promotion: {
            promotionId?: string;
            /** Format: int64 */
            amount?: number;
            /** Format: int64 */
            refundAmount?: number;
            goodsDetail?: components["schemas"]["GoodsDetail"][];
            /** @enum {string} */
            scope?: "GLOBAL" | "SINGLE";
            /** @enum {string} */
            type?: "COUPON" | "DISCOUNT";
        };
        Refund: {
            refundId?: string;
            outRefundNo?: string;
            transactionId?: string;
            outTradeNo?: string;
            userReceivedAccount?: string;
            successTime?: string;
            createTime?: string;
            promotionDetail?: components["schemas"]["Promotion"][];
            amount?: components["schemas"]["Amount"];
            /** @enum {string} */
            channel?: "ORIGINAL" | "BALANCE" | "OTHER_BALANCE" | "OTHER_BANKCARD";
            /** @enum {string} */
            fundsAccount?: "UNSETTLED" | "AVAILABLE" | "UNAVAILABLE" | "OPERATION" | "BASIC" | "ECNY_BASIC";
            /** @enum {string} */
            status?: "SUCCESS" | "CLOSED" | "PROCESSING" | "ABNORMAL";
        };
        Detail: {
            /** Format: int32 */
            costPrice?: number;
            invoiceId?: string;
            goodsDetail?: components["schemas"]["GoodsDetail"][];
        };
        PayCodeDto: {
            /**
             * Format: int32
             * @description 商品描述
             */
            businessType?: number;
            description?: string;
            outTradeNo?: string;
            attach?: string;
            goodsTag?: string;
            supportFapiao?: boolean;
            amount?: components["schemas"]["Amount"];
            payer?: components["schemas"]["Payer"];
            detail?: components["schemas"]["Detail"];
            sceneInfo?: components["schemas"]["SceneInfo"];
            settleInfo?: components["schemas"]["SettleInfo"];
        };
        Payer: {
            authCode?: string;
        };
        SceneInfo: {
            payerClientIp?: string;
            deviceId?: string;
            storeInfo?: components["schemas"]["StoreInfo"];
        };
        SettleInfo: {
            profitSharing?: boolean;
        };
        StoreInfo: {
            id?: string;
            name?: string;
            areaCode?: string;
            address?: string;
        };
        PrepayResponse: {
            amount?: components["schemas"]["TransactionAmount"];
            appid?: string;
            mchid?: string;
            attach?: string;
            bankType?: string;
            outTradeNo?: string;
            payer?: components["schemas"]["TransactionPayer"];
            promotionDetail?: components["schemas"]["PromotionDetail"][];
            successTime?: string;
            /** @enum {string} */
            tradeState?: "SUCCESS" | "REFUND" | "NOTPAY" | "CLOSED" | "REVOKED" | "USERPAYING" | "PAYERROR" | "ACCEPT";
            tradeStateDesc?: string;
            /** @enum {string} */
            tradeType?: "JSAPI" | "NATIVE" | "APP" | "MICROPAY" | "MWEB" | "FACEPAY";
            transactionId?: string;
        };
        PromotionDetail: {
            couponId?: string;
            name?: string;
            /** @enum {string} */
            scope?: "GLOBAL" | "SINGLE";
            /** @enum {string} */
            type?: "CASH" | "NOCASH";
            /** Format: int32 */
            amount?: number;
            stockId?: string;
            /** Format: int32 */
            wechatpayContribute?: number;
            /** Format: int32 */
            merchantContribute?: number;
            /** Format: int32 */
            otherContribute?: number;
            currency?: string;
            goodsDetail?: components["schemas"]["PromotionGoodsDetail"][];
        };
        PromotionGoodsDetail: {
            goodsId?: string;
            /** Format: int32 */
            quantity?: number;
            /** Format: int32 */
            unitPrice?: number;
            /** Format: int32 */
            discountAmount?: number;
            goodsRemark?: string;
        };
        TransactionAmount: {
            currency?: string;
            payerCurrency?: string;
            /** Format: int32 */
            payerTotal?: number;
            /** Format: int32 */
            total?: number;
        };
        TransactionPayer: {
            spOpenid?: string;
            subOpenid?: string;
        };
        /** @description 支付时传递的参数 */
        WxPayReqDto: {
            /**
             * Format: int32
             * @description 业务类型
             */
            businessType?: number;
            description?: string;
            outTradeNo?: string;
            timeExpire?: string;
            attach?: string;
            notifyUrl?: string;
            goodsTag?: string;
            limitPay?: ("NO_BALANCE" | "NO_CREDIT" | "NO_DEBIT" | "BALANCE_ONLY")[];
            supportFapiao?: boolean;
            amount?: components["schemas"]["Amount"];
            payer?: components["schemas"]["Payer"];
            detail?: components["schemas"]["Detail"];
            sceneInfo?: components["schemas"]["SceneInfo"];
            settleInfo?: components["schemas"]["SettleInfo"];
        };
        PrepayWithRequestPaymentResponse: {
            appId?: string;
            nonceStr?: string;
            packageVal?: string;
            signType?: string;
            paySign?: string;
            timeStamp?: string;
        };
        RString: {
            /** Format: int32 */
            code?: number;
            msg?: string;
            data?: string;
        };
        /** @description 微信支付配置 */
        WechatPaymentConfig: {
            /** @description UUID主键 */
            id?: string;
            /**
             * Format: int32
             * @description 业务类型
             */
            businessType?: number;
            /** @description 微信商户ID */
            merchantId?: string;
            /** @description 微信AppID */
            appId?: string;
            /** @description API密钥(v3) */
            apiV3Key?: string;
            /** @description 私钥(v3) */
            privateKeyPath?: string;
            /** @description cert地址路径 */
            privateCertPath?: string;
            /** @description 商户序列号 */
            mchSerialNo?: string;
            /** @description 默认回调地址 */
            notifyUrl?: string;
            /** @description 配置状态 */
            status?: string;
            /**
             * Format: date-time
             * @description 创建时间
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description 最后更新时间
             */
            updatedAt?: string;
        };
        /** @description 微信回调配置 */
        WechatCallbackConfig: {
            /** @description UUID主键 */
            id?: string;
            /**
             * Format: int32
             * @description 业务类型
             */
            businessType?: number;
            /** @description 回调地址 */
            notifyUrl?: string;
            /** @description 商户ID */
            merchantId?: string;
            /** @description 微信AppID */
            appId?: string;
            /** @description API密钥(v3) */
            apiV3Key?: string;
            /** @description 私钥(v3) */
            privateKeyPath?: string;
            /** @description cert地址路径 */
            privateCertPath?: string;
            /** @description 商户序列号 */
            mchSerialNo?: string;
            /**
             * Format: int64
             * @description 配置状态
             */
            status?: number;
            /**
             * Format: date-time
             * @description 创建时间
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description 最后更新时间
             */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    wxrefund: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Refund"];
                };
            };
        };
    };
    handleWeChatPayRefund: {
        parameters: {
            query?: never;
            header: {
                "Wechatpay-Signature": string;
                "Wechatpay-Nonce": string;
                "Wechatpay-Timestamp": string;
                "Wechatpay-Serial": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    handleWeChatPayTransaction: {
        parameters: {
            query?: never;
            header: {
                "Wechatpay-Signature": string;
                "Wechatpay-Nonce": string;
                "Wechatpay-Timestamp": string;
                "Wechatpay-Serial": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    wxpayByPayCode: {
        parameters: {
            query: {
                payCodeDto: components["schemas"]["PayCodeDto"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PrepayResponse"];
                };
            };
        };
    };
    wxjsapi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WxPayReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PrepayWithRequestPaymentResponse"];
                };
            };
        };
    };
    aliPay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RString"];
                };
            };
        };
    };
    getpayconfig: {
        parameters: {
            query: {
                businessType: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WechatPaymentConfig"];
                };
            };
        };
    };
    getCallBackConfig: {
        parameters: {
            query: {
                businessType: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WechatCallbackConfig"];
                };
            };
        };
    };
}
