/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/store/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询【请填写功能名称】列表
         * @description system:store:list
         */
        post: operations["list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导出【请填写功能名称】列表
         * @description system:store:export
         */
        post: operations["export"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改【请填写功能名称】
         * @description system:store:edit
         */
        post: operations["edit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/del": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 删除【请填写功能名称】
         * @description system:store:remove
         */
        post: operations["remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新增【请填写功能名称】
         * @description system:store:add
         */
        post: operations["add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询【请填写功能名称】列表
         * @description system:product:list
         */
        post: operations["list_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导出【请填写功能名称】列表
         * @description system:product:export
         */
        post: operations["export_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改【请填写功能名称】
         * @description system:product:edit
         */
        post: operations["edit_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/del": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 删除【请填写功能名称】
         * @description system:product:remove
         */
        post: operations["remove_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新增【请填写功能名称】
         * @description system:product:add
         */
        post: operations["add_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/couponOnUser/remote/useCoupon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 使用优惠券 */
        post: operations["use"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/couponOnUser/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询用户和优惠券之间的关联列表
         * @description system:user:list
         */
        post: operations["list_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/couponOnUser/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导出用户和优惠券之间的关联列表
         * @description system:user:export
         */
        post: operations["export_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/couponOnUser/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改用户和优惠券之间的关联
         * @description system:user:edit
         */
        post: operations["edit_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/couponOnUser/del": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 删除用户和优惠券之间的关联
         * @description system:user:remove
         */
        post: operations["remove_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/couponOnUser/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新增用户和优惠券之间的关联
         * @description system:user:add
         */
        post: operations["add_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coupon/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询优惠券列表
         * @description system:coupon:list
         */
        post: operations["list_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coupon/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导出优惠券列表
         * @description system:coupon:export
         */
        post: operations["export_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coupon/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改优惠券
         * @description system:coupon:edit
         */
        post: operations["edit_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coupon/del": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 删除优惠券
         * @description system:coupon:remove
         */
        post: operations["remove_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coupon/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新增优惠券
         * @description system:coupon:add
         */
        post: operations["add_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banner-img/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询轮播图列表
         * @description system:img:list
         */
        post: operations["list_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banner-img/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导出轮播图列表
         * @description system:img:export
         */
        post: operations["export_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banner-img/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改轮播图
         * @description system:img:edit
         */
        post: operations["edit_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banner-img/del": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 删除轮播图
         * @description system:img:remove
         */
        post: operations["remove_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banner-img/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新增轮播图
         * @description system:img:add
         */
        post: operations["add_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取【请填写功能名称】详细信息
         * @description system:store:query
         */
        get: operations["getInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取【请填写功能名称】详细信息
         * @description system:product:query
         */
        get: operations["getInfo_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/couponOnUser/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取用户和优惠券之间的关联详细信息
         * @description system:user:query
         */
        get: operations["getInfo_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coupon/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取优惠券详细信息
         * @description system:coupon:query
         */
        get: operations["getInfo_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/banner-img/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取轮播图详细信息
         * @description system:img:query
         */
        get: operations["getInfo_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 【请填写功能名称】 */
        CouponOnStore: {
            createBy?: string;
            /** Format: date-time */
            createTime?: string;
            updateBy?: string;
            /** Format: date-time */
            updateTime?: string;
            remark?: string;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNum?: number;
            params?: {
                [key: string]: Record<string, never>;
            };
            /** @description 主键id */
            id?: string;
            /** @description 优惠券id */
            couponId?: string;
            /** @description 优惠券名称 */
            copuonName?: string;
            /** @description 商店id */
            storeId?: string;
            /** @description 商店名称 */
            storeName?: string;
            /** @description 运营商id */
            aclAgentId?: string;
            /** @description 大区代理商id */
            aclProviderId?: string;
            /** @description 品牌商id */
            aclTenantId?: string;
        };
        TableDataInfo: {
            /** Format: int64 */
            total?: number;
            rows?: Record<string, never>[];
            /** Format: int32 */
            code?: number;
            msg?: string;
        };
        AjaxResult: {
            error?: boolean;
            warn?: boolean;
            success?: boolean;
            empty?: boolean;
        } & {
            [key: string]: Record<string, never>;
        };
        /** @description 通过ids删除dto */
        DelDto: {
            /** @description id数组 */
            ids?: string[];
        };
        /** @description 【请填写功能名称】 */
        CouponOnProduct: {
            createBy?: string;
            /** Format: date-time */
            createTime?: string;
            updateBy?: string;
            /** Format: date-time */
            updateTime?: string;
            remark?: string;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNum?: number;
            params?: {
                [key: string]: Record<string, never>;
            };
            /** @description 主键id */
            id?: string;
            /** @description 优惠券id */
            couponId?: string;
            /** @description 优惠券名称 */
            copuonName?: string;
            /** @description 商品id */
            productId?: string;
            /** @description 商品名称 */
            productName?: string;
            /** @description 商品规格id */
            productSpecsId?: string;
            /** @description 商品规格名称 */
            productSpecsName?: string;
        };
        /** @description 用户优惠券关联表 */
        CouponOnUserModelDto: {
            /** @description 优惠券id */
            id?: string;
        };
        /** @description 【请填写功能名称】 */
        CouponOnUser: {
            createBy?: string;
            /** Format: date-time */
            createTime?: string;
            updateBy?: string;
            /** Format: date-time */
            updateTime?: string;
            remark?: string;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNum?: number;
            params?: {
                [key: string]: Record<string, never>;
            };
            /** @description 主键id */
            id?: string;
            /** @description 优惠券id */
            couponId?: string;
            /** @description 优惠券名称 */
            copuonName?: string;
            /** @description 用户id */
            userId?: string;
            /** @description 用户名称 */
            userName?: string;
            /** @description 优惠券状态 */
            status?: string;
        };
        /** @description 优惠券 */
        Coupon: {
            createBy?: string;
            /** Format: date-time */
            createTime?: string;
            updateBy?: string;
            /** Format: date-time */
            updateTime?: string;
            remark?: string;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNum?: number;
            params?: {
                [key: string]: Record<string, never>;
            };
            /** @description 主键id */
            id?: string;
            /** @description 优惠卷名称 */
            name?: string;
            /** @description 类型【'DISCOUNT', 'REDUCTION', 'DEDUCTION', 'GIFT'】折扣，满减，抵扣，赠品 */
            type?: string;
            /**
             * Format: int32
             * @description 状态(0未领取,1未使用,2已使用,3已失效)
             */
            status?: number;
            /** @description 当type=DISCOUNT（折扣）时，打折数字 */
            discount?: number;
            /** @description 当type=REDUCTION（满减）时，满减的价格 */
            reductionPrice?: number;
            /** @description 当type=DEDUCTION（抵扣）时，抵扣的价格 */
            deductionPrice?: number;
            /** @description 当type=GIFT（赠品）时，商品id */
            productId?: string;
            /** @description 当type=GIFT（赠品）时，商品名称 */
            productName?: string;
            /** @description 当type=GIFT（赠品）时，商品规格id */
            productSpecsId?: string;
            /** @description 当type=GIFT（赠品）时，商品规格名称 */
            productSpecsName?: string;
            /** @description 消费的最低值可以使用 */
            minPrice?: number;
            /**
             * Format: int32
             * @description 是否规定商店使用:0否1是
             */
            isStore?: number;
            /**
             * Format: int32
             * @description 是否规定商品使用:0否1是
             */
            isProduct?: number;
            /**
             * Format: int32
             * @description 是否规定用户:0否1是
             */
            isUser?: number;
            /**
             * Format: int64
             * @description 剩余数量
             */
            quantity?: number;
        };
        /** @description 优惠券 */
        CouponDto: {
            createBy?: string;
            /** Format: date-time */
            createTime?: string;
            updateBy?: string;
            /** Format: date-time */
            updateTime?: string;
            remark?: string;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNum?: number;
            params?: {
                [key: string]: Record<string, never>;
            };
            /** @description 主键id */
            id?: string;
            /** @description 优惠卷名称 */
            name?: string;
            /** @description 类型【'DISCOUNT', 'REDUCTION', 'DEDUCTION', 'GIFT'】折扣，满减，抵扣，赠品 */
            type?: string;
            /** @description 当type=DISCOUNT（折扣）时，打折数字 */
            discount?: number;
            /** @description 当type=REDUCTION（满减）时，满减的价格 */
            reductionPrice?: number;
            /** @description 当type=DEDUCTION（抵扣）时，抵扣的价格 */
            deductionPrice?: number;
            /** @description 当type=GIFT（赠品）时，商品id */
            productId?: string;
            /** @description 当type=GIFT（赠品）时，商品名称 */
            productName?: string;
            /** @description 当type=GIFT（赠品）时，商品规格id */
            productSpecsId?: string;
            /** @description 当type=GIFT（赠品）时，商品规格名称 */
            productSpecsName?: string;
            /** @description 消费的最低值可以使用 */
            minPrice?: number;
            /**
             * Format: int32
             * @description 是否规定商店使用:0否1是
             */
            isStore?: number;
            /**
             * Format: int32
             * @description 是否规定商品使用:0否1是
             */
            isProduct?: number;
            /**
             * Format: int32
             * @description 是否规定用户:0否1是
             */
            isUser?: number;
            /**
             * Format: int64
             * @description 剩余数量
             */
            quantity?: number;
            /** @description 商店id */
            storeId?: string;
            /** @description 商店名称 */
            storeName?: string;
            /** @description 用户id */
            userId?: string;
        };
        /** @description 【请填写功能名称】 */
        BannerImg: {
            createBy?: string;
            /** Format: date-time */
            createTime?: string;
            updateBy?: string;
            /** Format: date-time */
            updateTime?: string;
            remark?: string;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNum?: number;
            params?: {
                [key: string]: Record<string, never>;
            };
            /** @description 主键id */
            id?: string;
            /** @description 品牌商id */
            aclTenantId?: string;
            /** @description 位置标识 */
            position?: string;
            /** @description 图片路径 */
            url?: string;
            /** @description 类型：【'OUTCHAIN','INCHAIN','NOTHING'】外链，内链，无 */
            chainType?: string;
            /** @description 点击跳转的url */
            jumpUrl?: string;
            /** @description 轮播图名称 */
            name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouponOnStore"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TableDataInfo"];
                };
            };
        };
    };
    export: {
        parameters: {
            query: {
                couponOnStore: components["schemas"]["CouponOnStore"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    edit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouponOnStore"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouponOnStore"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouponOnProduct"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TableDataInfo"];
                };
            };
        };
    };
    export_1: {
        parameters: {
            query: {
                couponOnProduct: components["schemas"]["CouponOnProduct"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    edit_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouponOnProduct"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    remove_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    add_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouponOnProduct"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    use: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouponOnUserModelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouponOnUser"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TableDataInfo"];
                };
            };
        };
    };
    export_2: {
        parameters: {
            query: {
                couponOnUser: components["schemas"]["CouponOnUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    edit_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouponOnUser"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    remove_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    add_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouponOnUser"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Coupon"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TableDataInfo"];
                };
            };
        };
    };
    export_3: {
        parameters: {
            query: {
                coupon: components["schemas"]["Coupon"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    edit_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Coupon"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    remove_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    add_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CouponDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BannerImg"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TableDataInfo"];
                };
            };
        };
    };
    export_4: {
        parameters: {
            query: {
                bannerImg: components["schemas"]["BannerImg"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    edit_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BannerImg"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    remove_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    add_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BannerImg"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    getInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    getInfo_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    getInfo_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    getInfo_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    getInfo_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
}
