/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/gen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["editSave"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gen/importTable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importTableSave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gen/{tableId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gen/synchDb/{tableName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["synchDb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gen/preview/{tableId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gen/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["genList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gen/genCode/{tableName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["genCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gen/download/{tableName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gen/db/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dataList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gen/column/{tableId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["columnList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gen/batchGenCode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["batchGenCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gen/{tableIds}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GenTable: {
            createBy?: string;
            /** Format: date-time */
            createTime?: string;
            updateBy?: string;
            /** Format: date-time */
            updateTime?: string;
            remark?: string;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNum?: number;
            params?: {
                [key: string]: Record<string, never>;
            };
            /** Format: int64 */
            tableId?: number;
            tableName: string;
            tableComment: string;
            subTableName?: string;
            subTableFkName?: string;
            className: string;
            tplCategory?: string;
            tplWebType?: string;
            packageName: string;
            moduleName: string;
            businessName: string;
            functionName: string;
            functionAuthor: string;
            genType?: string;
            genPath?: string;
            pkColumn?: components["schemas"]["GenTableColumn"];
            subTable?: components["schemas"]["GenTable"];
            columns?: components["schemas"]["GenTableColumn"][];
            options?: string;
            treeCode?: string;
            treeParentCode?: string;
            treeName?: string;
            /** Format: int64 */
            parentMenuId?: number;
            parentMenuName?: string;
            crud?: boolean;
            sub?: boolean;
            tree?: boolean;
        };
        GenTableColumn: {
            createBy?: string;
            /** Format: date-time */
            createTime?: string;
            updateBy?: string;
            /** Format: date-time */
            updateTime?: string;
            remark?: string;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNum?: number;
            params?: {
                [key: string]: Record<string, never>;
            };
            /** Format: int64 */
            columnId?: number;
            /** Format: int64 */
            tableId?: number;
            columnName?: string;
            columnComment?: string;
            columnType?: string;
            javaType?: string;
            javaField: string;
            isPk?: string;
            isIncrement?: string;
            isRequired?: string;
            isInsert?: string;
            isEdit?: string;
            isList?: string;
            isQuery?: string;
            queryType?: string;
            htmlType?: string;
            dictType?: string;
            /** Format: int32 */
            sort?: number;
            required?: boolean;
            list?: boolean;
            pk?: boolean;
            insert?: boolean;
            superColumn?: boolean;
            usableColumn?: boolean;
            edit?: boolean;
            query?: boolean;
            capJavaField?: string;
            increment?: boolean;
        };
        AjaxResult: {
            error?: boolean;
            success?: boolean;
            warn?: boolean;
            empty?: boolean;
        } & {
            [key: string]: Record<string, never>;
        };
        TableDataInfo: {
            /** Format: int64 */
            total?: number;
            rows?: Record<string, never>[];
            /** Format: int32 */
            code?: number;
            msg?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    editSave: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenTable"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    importTableSave: {
        parameters: {
            query: {
                tables: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    getInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    synchDb: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    genList: {
        parameters: {
            query: {
                genTable: components["schemas"]["GenTable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TableDataInfo"];
                };
            };
        };
    };
    genCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dataList: {
        parameters: {
            query: {
                genTable: components["schemas"]["GenTable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TableDataInfo"];
                };
            };
        };
    };
    columnList: {
        parameters: {
            query: {
                tableId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TableDataInfo"];
                };
            };
        };
    };
    batchGenCode: {
        parameters: {
            query: {
                tables: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableIds: number[];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
}
