/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/wx/ticket/verify-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/ticket/use-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["useTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/store/getStoreDetail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 查询店铺详情 */
        post: operations["getStoreDetail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/store/findnearstore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 查询最近30公里以内的门店 */
        post: operations["getNearStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/startTable/priceAnddeposite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 选择开台方式之后 查询球桌的价格和押金 */
        post: operations["queryPriceAndDeposite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/preLogin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 微信预登录 */
        post: operations["preLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/post/removePost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除帖子 */
        post: operations["removePost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/post/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发布帖子 */
        post: operations["publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/post/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 分页查询所有帖子 */
        post: operations["detail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/post/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 点赞功能 */
        post: operations["like"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/post/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 关注用户 */
        post: operations["follow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/post/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 查询帖子详情 */
        post: operations["detail_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/post/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 评论功能 */
        post: operations["comment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/pay/wx/walletPay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 钱包支付 */
        post: operations["pay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/pay/wx/returnmoney": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["returnWalletMoney"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 微信登录 */
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/addreservation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description 付款成功之后添加记录 */
        post: operations["addReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/startTable/{tableId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description 根据id查询桌子详情 */
        get: operations["gettableinfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wx/get_sts_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description sts获取临时token */
        get: operations["generateStsToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/getdetail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReservation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResult: {
            success?: boolean;
            /** Format: int32 */
            code?: number;
            message?: string;
            data?: Record<string, never>;
        };
        UseTicketRequest: {
            ticketId?: string;
        };
        GetStoreDetailDto: {
            storeId?: string;
        };
        NearStoreVo: {
            /** @description 店铺唯一标识，可使用UUID等方式生成 */
            id?: string;
            /** @description 店铺名称 */
            storeName?: string;
            /** @description 门店经纬度，存储经纬度数组，如[117.232191,31.837573] */
            longitudeLatitude?: string;
            /** @description 门店详细地址，如中国视界A4栋0413 */
            detailedAddress?: string;
            /** @description 店铺所在地，如安徽省/合肥市/蜀山区 */
            storeLocation?: string;
            /** @description 当前球桌价格 */
            lowPrice?: number;
            /**
             * Format: int32
             * @description 空闲桌球桌数
             */
            taiqiufreeTablenum?: number;
            /**
             * Format: int32
             * @description 空闲棋牌数
             */
            qipaifreeTablenum?: number;
            /** @description 店铺手机号 */
            phone?: string;
        };
        RNearStoreVo: {
            /** Format: int32 */
            code?: number;
            msg?: string;
            data?: components["schemas"]["NearStoreVo"];
        };
        GetNearStoreDto: {
            /** Format: double */
            longitude?: number;
            /** Format: double */
            latitude?: number;
            /** Format: int32 */
            pageNum?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        TableDataInfo: {
            /** Format: int64 */
            total?: number;
            rows?: Record<string, never>[];
            /** Format: int32 */
            code?: number;
            msg?: string;
        };
        R: {
            /** Format: int32 */
            code?: number;
            msg?: string;
            data?: Record<string, never>;
        };
        /** @description 预登录传递参数 */
        PreLoginDto: {
            /** @description 微信授权码 */
            jscode?: string;
            /** @description appId */
            appId?: string;
        };
        RString: {
            /** Format: int32 */
            code?: number;
            msg?: string;
            data?: string;
        };
        PublishPostDto: {
            /** @description 帖子的文本内容 */
            content?: string;
            /**
             * Format: double
             * @description 经度
             */
            latitude?: number;
            /**
             * Format: double
             * @description 纬度
             */
            longitude?: number;
            /**
             * Format: int32
             * @description 媒体类型（1: 图片, 2: 视频）
             */
            mediaType?: number;
            /** @description 文章图片 */
            images?: string[];
        };
        PostPageRequestDto: {
            /** Format: int32 */
            pageNum?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        OrderItem: {
            column?: string;
            asc?: boolean;
        };
        PagePostVo: {
            records?: components["schemas"]["PostVo"][];
            /** Format: int64 */
            total?: number;
            /** Format: int64 */
            size?: number;
            /** Format: int64 */
            current?: number;
            orders?: components["schemas"]["OrderItem"][];
            optimizeCountSql?: components["schemas"]["PagePostVo"];
            searchCount?: components["schemas"]["PagePostVo"];
            optimizeJoinOfCountSql?: boolean;
            /** Format: int64 */
            maxLimit?: number;
            countId?: string;
            /** Format: int64 */
            pages?: number;
        };
        PostVo: {
            /**
             * @description 帖子ID
             * @example 123456
             */
            id?: string;
            /** @description 作者昵称 */
            userName?: string;
            /** @description 作者头像 */
            imageUrl?: string;
            /** @description 作者ID */
            authorId?: string;
            /** @description 帖子内容 */
            content?: string;
            /**
             * Format: int32
             * @description 媒体类型（0: 图片, 1: 视频）
             */
            mediaType?: number;
            /** @description 动态中的图片列表 */
            imageUrls?: string[];
            /** @description 视频地址url */
            videoUrl?: string;
            /**
             * Format: int32
             * @description 点赞数
             * @example 500
             */
            likeCount?: number;
            /**
             * Format: int32
             * @description 评论数
             * @example 100
             */
            commentCount?: number;
            /**
             * Format: int32
             * @description 分享数
             * @example 20
             */
            shareCount?: number;
            /**
             * Format: int32
             * @description 查看次数
             * @example 1000
             */
            viewCount?: number;
            /**
             * Format: date-time
             * @description 创建时间
             */
            createdAt?: string;
            /**
             * @description 当前用户是否已点赞此动态
             * @example true
             */
            isLiked?: boolean;
            /**
             * @description 当前用户是否已关注该动态的作者
             * @example false
             */
            isFollowed?: boolean;
        };
        RPagePostVo: {
            /** Format: int32 */
            code?: number;
            msg?: string;
            data?: components["schemas"]["PagePostVo"];
        };
        LikesBehaviorDto: {
            /** @description 帖子等ID */
            postId?: string;
            /**
             * Format: int32
             * @description 喜欢操作方式 0点赞 1取消点赞
             */
            operation?: number;
        };
        FollowBehaviorDto: {
            /** @description 帖子id */
            postId?: string;
            /** @description 被关注作者的id */
            authorId?: string;
            /**
             * Format: int32
             * @description 操作方式 0关注 1取消关注
             */
            operation?: number;
        };
        CommentRequestdto: {
            /** @description 帖子ID 如果是针对评论回复此处为null */
            postId?: string;
            /** @description 父级评论ID 如果是针对帖子评论 此处为null */
            parentId?: string;
            /** @description 评论内容 */
            textContent?: string;
            /** @description 媒体类型（1: 图片, 2: 视频） */
            mediaType?: string;
            /** @description 媒体文件的URL地址（如图片链接或视频链接） */
            mediaUrl?: string;
        };
        TableOpeningRequest: {
            tableId?: string;
            userId?: string;
            startTime?: string;
            endTime?: string;
            /** Format: int64 */
            personCount?: number;
            /** @enum {string} */
            bookingType?: "SELF_SERVICE" | "GROUP_PURCHASE" | "TEAM_MATCH" | "TIMED" | "CASH";
            otherUserId?: string;
            /** @enum {string} */
            orderPayWayEnum?: "WECHAT" | "ALIPAY" | "CASH" | "MEMBER" | "OTHER";
            tableOpeningType?: string;
            /** Format: int32 */
            isAiReferee?: number;
            paymentMethod?: string;
            factAmount?: number;
            orderAmount?: number;
        };
        LoginRequestDto: {
            /** @description 昵称 */
            nickName?: string;
            /** @description 获取手机号code */
            phoneCode?: string;
            /** @description appId */
            appId?: string;
        };
        LoginVo: {
            /** @description token */
            token?: string;
        };
        RLoginVo: {
            /** Format: int32 */
            code?: number;
            msg?: string;
            data?: components["schemas"]["LoginVo"];
        };
        /** @description 文件上传所需的临时凭证与路径信息 */
        FileUploadVo: {
            /**
             * @description 临时凭证
             * @example a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0
             */
            signature?: string;
            /**
             * @description 上传目录路径
             * @example /uploads/2025/05/22/
             */
            dir?: string;
            /**
             * @description 域名地址
             * @example https://oss.example.com
             */
            domainName?: string;
        };
        RFileUploadVo: {
            /** Format: int32 */
            code?: number;
            msg?: string;
            data?: components["schemas"]["FileUploadVo"];
        };
        AjaxResult: {
            error?: boolean;
            success?: boolean;
            warn?: boolean;
            empty?: boolean;
        } & {
            [key: string]: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    verifyTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResult"];
                };
            };
        };
    };
    useTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UseTicketRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResult"];
                };
            };
        };
    };
    getStoreDetail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetStoreDetailDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RNearStoreVo"];
                };
            };
        };
    };
    getNearStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetNearStoreDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TableDataInfo"];
                };
            };
        };
    };
    queryPriceAndDeposite: {
        parameters: {
            query: {
                tableId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["R"];
                };
            };
        };
    };
    preLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreLoginDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RString"];
                };
            };
        };
    };
    removePost: {
        parameters: {
            query: {
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["R"];
                };
            };
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishPostDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["R"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostPageRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RPagePostVo"];
                };
            };
        };
    };
    like: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LikesBehaviorDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["R"];
                };
            };
        };
    };
    follow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowBehaviorDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["R"];
                };
            };
        };
    };
    detail_1: {
        parameters: {
            query: {
                postId: number;
                pageNum: number;
                pageSize: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["R"];
                };
            };
        };
    };
    comment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentRequestdto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["R"];
                };
            };
        };
    };
    pay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TableOpeningRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["R"];
                };
            };
        };
    };
    returnWalletMoney: {
        parameters: {
            query: {
                amount: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["R"];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RLoginVo"];
                };
            };
        };
    };
    addReservation: {
        parameters: {
            query: {
                tableId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["R"];
                };
            };
        };
    };
    gettableinfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tableId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["R"];
                };
            };
        };
    };
    generateStsToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RFileUploadVo"];
                };
            };
        };
    };
    getReservation: {
        parameters: {
            query: {
                tableId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
}
