/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/reservation/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询预约信息列表
         * @description system:reservation:list
         */
        post: operations["list"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservation/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导出预约信息列表
         * @description system:reservation:export
         */
        post: operations["export"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservation/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改预约信息
         * @description system:reservation:edit
         */
        post: operations["edit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservation/del": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 删除预约信息
         * @description system:reservation:remove
         */
        post: operations["remove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservation/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新增预约信息
         * @description system:reservation:add
         */
        post: operations["add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/shift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getShiftList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/remote/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 远程修改订单信息 */
        post: operations["remoteEdit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/remote/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 远程新增订单信息 */
        post: operations["remoteAdd"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/orderList": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["orderList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 查询订单列表 */
        post: operations["list_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/getCloseShiftAmount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 结算订单计算结果订单 */
        post: operations["getCloseShiftAmount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 导出订单列表 */
        post: operations["export_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/endOrder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 主动结束订单 */
        post: operations["endOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 修改订单信息 */
        post: operations["edit_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/del": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 删除订单信息 */
        post: operations["remove_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新增订单信息 */
        post: operations["add_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/OrderItem/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询订单商品明细列表
         * @description system:OrderItem:list
         */
        post: operations["list_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/OrderItem/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导出订单商品明细列表
         * @description system:OrderItem:export
         */
        post: operations["export_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/OrderItem/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改订单商品明细
         * @description system:OrderItem:edit
         */
        post: operations["edit_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/OrderItem/del": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 删除订单商品明细
         * @description system:OrderItem:remove
         */
        post: operations["remove_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/OrderItem/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新增订单商品明细
         * @description system:OrderItem:add
         */
        post: operations["add_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservation/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取预约信息详细信息
         * @description system:reservation:query
         */
        get: operations["getInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取订单信息详细信息 */
        get: operations["getInfo_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/remote/getDetail/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 远程获取订单信息详细信息 */
        get: operations["remoteGetDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/OrderItem/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取订单商品明细详细信息
         * @description system:OrderItem:query
         */
        get: operations["getInfo_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 预约信息 */
        ReservationInfo: {
            createBy?: string;
            /** Format: date-time */
            createTime?: string;
            updateBy?: string;
            /** Format: date-time */
            updateTime?: string;
            remark?: string;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNum?: number;
            params?: {
                [key: string]: Record<string, never>;
            };
            /** @description 预约ID，雪花算法生成 */
            id?: string;
            /** @description 台桌ID（关联table_info.id） */
            tableId?: string;
            /** @description 预约人手机号 */
            userPhone?: string;
            /** @description 预约人姓名 */
            userName?: string;
            /**
             * Format: int64
             * @description 预约人数
             */
            userCount?: number;
            /**
             * Format: date-time
             * @description 预约开始时间
             */
            reserveStartTime?: string;
            /**
             * Format: date-time
             * @description 预约结束时间
             */
            reserveEndTime?: string;
            /**
             * Format: int64
             * @description 预约时长（分钟）
             */
            reserveMinutes?: number;
            /**
             * @description 预约状态（PENDING-待确认, CANCELLED-已取消, USED-已使用）
             * @enum {string}
             */
            reserveStatus?: "PENDING-待确认" | "CANCELLED-已取消" | "USED-已使用";
            /** @description 取消原因 */
            cancelReason?: string;
            /**
             * Format: date-time
             * @description 取消时间
             */
            cancelTime?: string;
            /**
             * Format: date-time
             * @description 实际开台时间
             */
            actualStartTime?: string;
            /** @description 开台操作员 */
            openOperator?: string;
            /** @description 用户id */
            userId?: string;
            /** @description 预约金 */
            amount?: number;
        };
        TableDataInfo: {
            /** Format: int64 */
            total?: number;
            rows?: Record<string, never>[];
            /** Format: int32 */
            code?: number;
            msg?: string;
        };
        AjaxResult: {
            error?: boolean;
            success?: boolean;
            warn?: boolean;
            empty?: boolean;
        } & {
            [key: string]: Record<string, never>;
        };
        /** @description 通过ids删除dto */
        DelDto: {
            /** @description id数组 */
            ids?: string[];
        };
        /** @description 交接班 */
        Shift: {
            createBy?: string;
            /** Format: date-time */
            createTime?: string;
            updateBy?: string;
            /** Format: date-time */
            updateTime?: string;
            remark?: string;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNum?: number;
            params?: {
                [key: string]: Record<string, never>;
            };
            /**
             * Format: int64
             * @description 唯一标识
             */
            id?: number;
            /** @description 店铺id */
            storeId?: string;
            /**
             * Format: int64
             * @description 用户id
             */
            userId?: number;
            /**
             * Format: int64
             * @description 总订单数
             */
            totalOrder?: number;
            /** @description 总销售额 */
            totalPrice?: number;
            /** @description 钱箱金额 */
            box?: number;
            /** @description 退款金额 */
            returnPrice?: number;
            /** @description 无票退款金额 */
            noReturnPrice?: number;
            /**
             * Format: int32
             * @description 无票订单数
             */
            noOrder?: number;
        };
        RShift: {
            /** Format: int32 */
            code?: number;
            msg?: string;
            data?: components["schemas"]["Shift"];
        };
        OrderInfoModel: {
            createBy?: string;
            /** Format: date-time */
            createTime?: string;
            updateBy?: string;
            /** Format: date-time */
            updateTime?: string;
            remark?: string;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNum?: number;
            params?: {
                [key: string]: Record<string, never>;
            };
            id?: string;
            storeId?: string;
            reservationId?: string;
            tableId?: string;
            tableName?: string;
            tableNumber?: string;
            userId?: string;
            /** @enum {string} */
            orderStatus?: "UNPAID" | "PAID" | "FAIL" | "DOING" | "CANCEL" | "PARTPAID" | "WAITPICK";
            /** @enum {string} */
            channel?: "MINIPROGRAM" | "CASHREGISTER";
            tableTypeId?: string;
            tableTypeName?: string;
            tableLevelId?: string;
            tableLevelName?: string;
            /** Format: int32 */
            isReservation?: number;
            userName?: string;
            userPhone?: string;
            /** Format: int64 */
            userCount?: number;
            orderAmount?: number;
            deposit?: number;
            /** Format: int32 */
            isDepositFree?: number;
            /** @enum {string} */
            tableOpeningType?: "SELF_SERVICE" | "GROUP_PURCHASE" | "TEAM_MATCH" | "TIMED" | "CASH";
            couponId?: string;
            /** @enum {string} */
            paymentMethod?: "SOLEPAYMENT" | "AAPAYMENT" | "WINNERPAYMENT";
            /** @enum {string} */
            paymentType?: "WECHAT" | "ALIPAY" | "CASH" | "MEMBER" | "OTHER";
            reservationUserId?: string;
            reservationUserPaymentAmount?: number;
            tableOpeningUserPaymentAmount?: number;
            tableOpeningUserOrderId?: string;
            /** Format: int32 */
            isAiReferee?: number;
            aclAgentId?: string;
            aclAgentName?: string;
            actualAmount?: number;
            aclProviderId?: string;
            aclProviderName?: string;
            aclTenantId?: string;
            aclTenantName?: string;
            tableThaliId?: string;
            tableThaliName?: string;
            tableThaliPrice?: number;
            /** Format: int64 */
            tableThaliTime?: number;
            refundAmount?: number;
            /** Format: date-time */
            closeTableStart?: string;
            /** Format: date-time */
            closeTableEnd?: string;
            minimumConsumption?: number;
            /** Format: int32 */
            timedTime?: number;
            /** Format: date-time */
            orderEndTime?: string;
        };
        OrderDto: {
            id?: string;
            storeId?: string;
            /** Format: date-time */
            startTime?: string;
            /** Format: date-time */
            endTime?: string;
            /** @enum {string} */
            channel?: "MINIPROGRAM" | "CASHREGISTER";
            tableId?: string;
        };
        /** @description 订单信息 */
        Order: {
            createBy?: string;
            /** Format: date-time */
            createTime?: string;
            updateBy?: string;
            /** Format: date-time */
            updateTime?: string;
            remark?: string;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNum?: number;
            params?: {
                [key: string]: Record<string, never>;
            };
            /** @description 开始时间 */
            startTime?: string;
            /** @description 结束时间 */
            endTime?: string;
            /** @description 台桌号 */
            tableNumber?: string;
            /** @description 订单ID */
            id?: string;
            /** @description 店铺ID */
            storeId?: string;
            /** @description 台桌ID */
            tableId?: string;
            /** @description 台桌名称 */
            tableName?: string;
            /** @description 用户ID */
            userId?: string;
            /**
             * @description 订单状态
             * @enum {string}
             */
            orderStatus?: "UNPAID" | "PAID" | "FAIL" | "DOING" | "CANCEL" | "PARTPAID" | "WAITPICK";
            /** @description 渠道 */
            channel?: string;
            /** @description 台桌类型id */
            tableTypeId?: string;
            /** @description 台桌类型名称 */
            tableTypeName?: string;
            /** @description 台桌分组id */
            tableLevelId?: string;
            /** @description 台桌分组名称 */
            tableLevelName?: string;
            /**
             * Format: int32
             * @description 是否是预约单（0:否，1:是）
             */
            isReservation?: number;
            /**
             * Format: int32
             * @description 订单类型（0:台桌 1：商品）
             */
            orderType?: number;
            /** @description 订单金额 */
            orderAmount?: number;
            /** @description 押金 */
            deposit?: number;
            /**
             * Format: int32
             * @description 是否免押金（0:否，1:是）
             */
            isDepositFree?: number;
            /**
             * @description 开台类型
             * @enum {string}
             */
            tableOpeningType?: "SELF_SERVICE" | "GROUP_PURCHASE" | "TEAM_MATCH" | "TIMED" | "CASH";
            /** @description 预约id */
            reservationId?: string;
            /** @description 优惠券ID */
            couponId?: string;
            /** @description 付款方式 */
            paymentMethod?: string;
            /** @description 支付类型 */
            paymentType?: string;
            /** @description 预约用户ID */
            reservationUserId?: string;
            /** @description 预约用户付款金额 */
            reservationUserPaymentAmount?: number;
            /** @description 开台用户付款金额 */
            tableOpeningUserPaymentAmount?: number;
            /** @description 开台人订单ID */
            tableOpeningUserOrderId?: string;
            /**
             * Format: int32
             * @description 是否带AI裁判（0:否，1:是）
             */
            isAiReferee?: number;
            /** @description 运营商id */
            aclAgentId?: string;
            /** @description 运应商名称 */
            aclAgentName?: string;
            /** @description 服务商id */
            aclProviderId?: string;
            /** @description 服务商名称 */
            aclProviderName?: string;
            /** @description 品牌商id */
            aclTenantName?: string;
            /** @description 品牌商名称 */
            aclTenantId?: string;
            /** @description 用户名 */
            userName?: string;
            /** @description 用户手机号码 */
            userPhone?: string;
            /**
             * Format: int64
             * @description 用户人数
             */
            userCount?: number;
            /** @description 实收金额 */
            actualAmount?: number;
            /** @description 退款金额 */
            refundAmount?: number;
            /**
             * Format: date-time
             * @description 支付时间
             */
            payTime?: string;
            /**
             * Format: date-time
             * @description 订单结束时间
             */
            orderEndTime?: string;
            /**
             * Format: date-time
             * @description 关台开始时间
             */
            closeTableStart?: string;
            /**
             * Format: date-time
             * @description 关台结束时间
             */
            closeTableEnd?: string;
            /** @description 最低消费(元) */
            minimumConsumption?: number;
            /**
             * Format: int32
             * @description 定时时长
             */
            timedTime?: number;
        };
        /** @description 订单商品明细 */
        OrderItem: {
            createBy?: string;
            /** Format: date-time */
            createTime?: string;
            updateBy?: string;
            /** Format: date-time */
            updateTime?: string;
            remark?: string;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNum?: number;
            params?: {
                [key: string]: Record<string, never>;
            };
            /** @description 主键 */
            id?: string;
            /**
             * @description 订单类型
             * @enum {string}
             */
            orderType?: "TABLE" | "CATEGORY";
            /** @description 关联的订单ID */
            orderId?: string;
            /**
             * Format: int64
             * @description 商品数量
             */
            categoryQuantity?: number;
            /** @description 商品价格 */
            categoryPrice?: number;
            /** @description 商品ID */
            categoryId?: string;
            /** @description 商品名称 */
            categoryName?: string;
            /** @description 商品规格id */
            categorySpecId?: string;
            /** @description 商品规格名称 */
            categorySpecsName?: string;
            /** @description 分类id */
            typeId?: string;
            /** @description 分类名称 */
            typeName?: string;
        };
        RReservationInfo: {
            /** Format: int32 */
            code?: number;
            msg?: string;
            data?: components["schemas"]["ReservationInfo"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationInfo"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TableDataInfo"];
                };
            };
        };
    };
    export: {
        parameters: {
            query: {
                reservationInfo: components["schemas"]["ReservationInfo"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    edit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationInfo"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    remove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    add: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationInfo"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    getShiftList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Shift"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RShift"];
                };
            };
        };
    };
    remoteEdit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderInfoModel"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    remoteAdd: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderInfoModel"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    orderList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TableDataInfo"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Order"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TableDataInfo"];
                };
            };
        };
    };
    getCloseShiftAmount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderInfoModel"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    export_1: {
        parameters: {
            query: {
                order: components["schemas"]["Order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    endOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderInfoModel"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    edit_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Order"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    remove_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    add_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Order"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderItem"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TableDataInfo"];
                };
            };
        };
    };
    export_2: {
        parameters: {
            query: {
                orderItem: components["schemas"]["OrderItem"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    edit_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderItem"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    remove_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DelDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    add_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderItem"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    getInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RReservationInfo"];
                };
            };
        };
    };
    getInfo_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    remoteGetDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
    getInfo_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AjaxResult"];
                };
            };
        };
    };
}
